on: push
name: Build and Deploy Github Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build and Deploy Zola
        uses: shalzz/zola-deploy-action@c5d34028ce487accf758a7c7a2b25c73946d1e99 # v0.17.2-1
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
